// One-line meanings for the fixed symbol vocabulary (assets/icons/symbols/).
// Kept short on purpose: Dream Echo is about *your* pattern, not a dream dictionary.
export const SYMBOL_MEANINGS: Record<string, string> = {
  bird: 'Freedom, perspective, and the wish to rise above.',
  cat: 'Independence, intuition, and quiet mystery.',
  cloud: 'Uncertainty, drifting thoughts, a view not yet clear.',
  crow: 'Messages, change, and what watches from the edges.',
  death: 'Endings that make room for something new.',
  desert: 'Emptiness, searching, and the space before a change.',
  door: 'Thresholds, choices, and new beginnings.',
  eye: 'Awareness, being seen, and seeing clearly.',
  fire: 'Passion, anger, transformation.',
  forest: 'The unknown, getting lost, and finding your own path.',
  grass: 'Growth, simplicity, and ordinary peace.',
  heart: 'Love, longing, and what you care about most.',
  house: 'The self, memory, and the places that shaped you.',
  key: 'Answers, access, and something waiting to be unlocked.',
  light: 'Clarity, hope, and guidance.',
  mask: 'The faces we show, and what hides behind them.',
  mirror: 'Self-reflection, duality, and hidden truths.',
  moon: 'Night, intuition, and the quiet parts of the mind.',
  mountain: 'Ambition, obstacles, and the long climb.',
  ocean: 'The vast unconscious, depth, and the unknown.',
  snake: 'Fear, healing, and transformation.',
  snow: 'Stillness, pause, and a clean slate.',
  stairs: 'Progress, effort, and moving between levels of life.',
  star: 'Wonder, guidance, and distant hopes.',
  sun: 'Energy, clarity, and warmth.',
  train: 'Life direction, timing, and being carried along.',
  water: 'Emotion, the unconscious, and change.',
  web: 'Connection, entanglement, and feeling caught.',
  wind: 'Change in the air, restlessness, and unseen forces.',
  wolf: 'Instinct, the shadow self, and untamed strength.',
};
